// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RockProjectBackend.Data;

#nullable disable

namespace RockProjectBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250628024620_UpdateImagesSeedData")]
    partial class UpdateImagesSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RockProjectBackend.Models.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlbumDestacado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CancionDestacada")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Resena")
                        .HasColumnType("text");

                    b.Property<string>("Subgenero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Artistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumDestacado = "Elvis Presley (1956)",
                            CancionDestacada = "Hound Dog",
                            Imagen = "https://direstraitsblog.com/wp-content/uploads/2017/08/Elvis-Presley-Dancing-Photo-Share-On-Facebook.jpg",
                            Nombre = "Elvis Presley",
                            Resena = "Considerado el 'Rey del Rock and Roll', su carisma y su fusión de country con rhythm and blues lo convirtieron en un ícono cultural que cambió la música para siempre.",
                            Subgenero = "Rockabilly / Rock and Roll"
                        },
                        new
                        {
                            Id = 2,
                            AlbumDestacado = "Chuck Berry Is on Top (1959)",
                            CancionDestacada = "Johnny B. Goode",
                            Imagen = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgYL3kbCF0JGUDKAK_iv1KLaojYu3v8RIq7SVnNaVJh-HewiOWhtn5qijLKSAZRVvr6VhBsXEmt7rQX80M_1AmdBFty-pSwCErjs78YrnIn_hyphenhyphen93Bl-j2zD4reZQ-GUh0lVt7EY9P8ooDg/s1600/chuck-berry-portrait.jpg",
                            Nombre = "Chuck Berry",
                            Resena = "Uno de los padres fundadores del rock, definió su sonido con su distintiva guitarra y letras que capturaban el espíritu de la juventud estadounidense.",
                            Subgenero = "Rock and Roll"
                        },
                        new
                        {
                            Id = 3,
                            AlbumDestacado = "Here's Little Richard (1957)",
                            CancionDestacada = "Tutti Frutti",
                            Imagen = "https://images.genius.com/9075cc90590d6536cbd710a4d8d7bb2d.1000x1000x1.jpg",
                            Nombre = "Little Richard",
                            Resena = "Con su energía explosiva, su piano frenético y su voz inconfundible, fue una fuerza pionera que inyectó extravagancia y dinamismo al rock and roll.",
                            Subgenero = "Rock and Roll"
                        },
                        new
                        {
                            Id = 4,
                            AlbumDestacado = "The 'Chirping' Crickets (1957)",
                            CancionDestacada = "Peggy Sue",
                            Imagen = "https://wallpapers.com/images/hd/painted-portrait-of-buddy-holly-and-the-crickets-xoyaqxyy7tvwvl52.jpg",
                            Nombre = "Buddy Holly",
                            Resena = "Un innovador compositor y guitarrista cuya carrera, aunque breve, influyó profundamente en la estructura de la música pop y el formato de las bandas de rock.",
                            Subgenero = "Rockabilly"
                        },
                        new
                        {
                            Id = 5,
                            AlbumDestacado = "Sgt. Pepper's Lonely Hearts Club Band (1967)",
                            CancionDestacada = "A Day in the Life",
                            Imagen = "https://storage.lacapitalmdp.com/2022/10/The-Beatles.jpg",
                            Nombre = "The Beatles",
                            Resena = "Originarios de Liverpool, los 'Fab Four' revolucionaron la música popular con su innovadora composición, armonías vocales y experimentación en el estudio.",
                            Subgenero = "Rock Psicodélico / Pop Rock"
                        },
                        new
                        {
                            Id = 6,
                            AlbumDestacado = "Exile on Main St. (1972)",
                            CancionDestacada = "(I Can't Get No) Satisfaction",
                            Imagen = "https://musicscore.ms/uploads/musicscore/performer_photos/the-rolling-stones-2433.jpg",
                            Nombre = "The Rolling Stones",
                            Resena = "La encarnación de la rebeldía del rock, con un sonido crudo basado en el blues y una actitud que los ha mantenido como una de las bandas más grandes durante décadas.",
                            Subgenero = "Blues Rock / Rock and Roll"
                        },
                        new
                        {
                            Id = 7,
                            AlbumDestacado = "Who's Next (1971)",
                            CancionDestacada = "Baba O'Riley",
                            Imagen = "https://www.thewho.com/wp-content/uploads/2017/09/1968-TheWho-Top-of-the-Pops.jpg",
                            Nombre = "The Who",
                            Resena = "Conocidos por sus óperas rock y sus explosivas actuaciones en vivo, The Who empujó los límites del sonido y la narrativa en la música rock.",
                            Subgenero = "Hard Rock / Rock"
                        },
                        new
                        {
                            Id = 8,
                            AlbumDestacado = "Led Zeppelin IV (1971)",
                            CancionDestacada = "Stairway to Heaven",
                            Imagen = "https://i.pinimg.com/originals/36/77/8a/36778adb3057e0f53aa42b110ab2a623.jpg",
                            Nombre = "Led Zeppelin",
                            Resena = "Pioneros del hard rock y el heavy metal, esta banda británica es célebre por sus poderosos riffs de guitarra y su épica musicalidad.",
                            Subgenero = "Hard Rock / Folk Rock"
                        },
                        new
                        {
                            Id = 9,
                            AlbumDestacado = "The Dark Side of the Moon (1973)",
                            CancionDestacada = "Money",
                            Imagen = "https://static01.nyt.com/images/2023/03/01/arts/28PINKY-FLOYD/28MOON-mediumSquareAt3X.jpg",
                            Nombre = "Pink Floyd",
                            Resena = "Maestros del rock progresivo y psicodélico, son conocidos por sus álbumes conceptuales, letras filosóficas y espectáculos en vivo elaborados.",
                            Subgenero = "Rock Progresivo / Psicodélico"
                        },
                        new
                        {
                            Id = 10,
                            AlbumDestacado = "Are You Experienced (1967)",
                            CancionDestacada = "Purple Haze",
                            Imagen = "https://1.bp.blogspot.com/-k6nAovVroGw/UJdePTJDwdI/AAAAAAAAFyQ/gZS2fVR0S1E/s1600/01+jimi-hendrix.jpg",
                            Nombre = "Jimi Hendrix",
                            Resena = "Considerado el guitarrista más influyente de la historia, redefinió las posibilidades del instrumento con su técnica innovadora y su uso de la distorsión y el feedback.",
                            Subgenero = "Rock Psicodélico / Hard Rock"
                        },
                        new
                        {
                            Id = 11,
                            AlbumDestacado = "A Night at the Opera (1975)",
                            CancionDestacada = "Bohemian Rhapsody",
                            Imagen = "https://i.pinimg.com/originals/29/02/99/290299f053e94daf1a016c3741bfff7a.jpg",
                            Nombre = "Queen",
                            Resena = "Liderados por el incomparable Freddie Mercury, fusionaron el glam, el hard rock y la ópera para crear un sonido grandilocuente y único.",
                            Subgenero = "Glam Rock / Hard Rock"
                        },
                        new
                        {
                            Id = 12,
                            AlbumDestacado = "The Rise and Fall of Ziggy Stardust...",
                            CancionDestacada = "Heroes",
                            Imagen = "https://www.rockandpop.cl/wp-content/uploads/2020/07/57e5442ffa083343d2f2b9eff320c7c9-768x791.jpg",
                            Nombre = "David Bowie",
                            Resena = "Un camaleón musical y cultural, Bowie constantemente reinventó su imagen y sonido, explorando géneros desde el glam hasta la electrónica.",
                            Subgenero = "Glam Rock / Art Rock"
                        },
                        new
                        {
                            Id = 13,
                            AlbumDestacado = "Highway 61 Revisited (1965)",
                            CancionDestacada = "Like a Rolling Stone",
                            Imagen = "https://a.1stdibscdn.com/lynn-goldsmith-photography-bob-dylan-straight-on-1976-for-sale/a_2432/1614719388387/dylan1_Final_master.jpg",
                            Nombre = "Bob Dylan",
                            Resena = "La voz de una generación, sus poéticas y socialmente conscientes letras transformaron la música folk y la elevaron a una forma de arte literario.",
                            Subgenero = "Folk Rock"
                        },
                        new
                        {
                            Id = 14,
                            AlbumDestacado = "The Doors (1967)",
                            CancionDestacada = "Light My Fire",
                            Imagen = "https://static.stereogum.com/uploads/2015/07/the_doors.jpgg",
                            Nombre = "The Doors",
                            Resena = "Con la poesía oscura de Jim Morrison y el sonido hipnótico de sus teclados, The Doors exploró los rincones más oscuros de la psique humana.",
                            Subgenero = "Rock Psicodélico"
                        },
                        new
                        {
                            Id = 15,
                            AlbumDestacado = "Cosmo's Factory (1970)",
                            CancionDestacada = "Fortunate Son",
                            Imagen = "https://www.dirtyrock.info/wp-content/uploads/2013/10/Creedence-Clearwater-Revival-reeditan-Box-set-en-noviembre.jpg",
                            Nombre = "Creedence Clearwater Revival",
                            Resena = "Liderados por John Fogerty, crearon un sonido distintivo de rock sureño con éxitos concisos y potentes que se convirtieron en himnos.",
                            Subgenero = "Swamp Rock / Roots Rock"
                        },
                        new
                        {
                            Id = 16,
                            AlbumDestacado = "Paranoid (1970)",
                            CancionDestacada = "Paranoid",
                            Imagen = "https://www.therockpit.net/wp-content/uploads/2021/08/blacksabbath-promo1-768x780.jpg",
                            Nombre = "Black Sabbath",
                            Resena = "Considerados los creadores del heavy metal, sus riffs oscuros y pesados, cortesía de Tony Iommi, sentaron las bases para todo un género.",
                            Subgenero = "Heavy Metal / Hard Rock"
                        },
                        new
                        {
                            Id = 17,
                            AlbumDestacado = "Back in Black (1980)",
                            CancionDestacada = "Back in Black",
                            Imagen = "https://images.genius.com/2c47d7d7061759b1776ba00f541392d2.1000x1000x1.jpg",
                            Nombre = "AC/DC",
                            Resena = "La personificación del rock and roll directo y sin concesiones. Su música se basa en riffs de guitarra simples, potentes y memorables.",
                            Subgenero = "Hard Rock"
                        },
                        new
                        {
                            Id = 18,
                            AlbumDestacado = "Hotel California (1976)",
                            CancionDestacada = "Hotel California",
                            Imagen = "https://www.rollingstone.com/wp-content/uploads/2019/01/the-eagles-are-boring.jpg",
                            Nombre = "Eagles",
                            Resena = "Maestros de las armonías vocales y del sonido californiano, mezclaron el country con el soft rock para crear algunas de las canciones más vendidas de la historia.",
                            Subgenero = "Soft Rock / Country Rock"
                        },
                        new
                        {
                            Id = 19,
                            AlbumDestacado = "Rumours (1977)",
                            CancionDestacada = "Go Your Own Way",
                            Imagen = "https://cdn-images.dzcdn.net/images/artist/ef23278cf3a67a3ca8404ddaa38699d4/500x500-000000-80-0-0.jpg",
                            Nombre = "Fleetwood Mac",
                            Resena = "Con una mezcla única de talento británico y estadounidense, crearon pop-rock sofisticado, marcado por sus complejas relaciones internas.",
                            Subgenero = "Soft Rock / Pop Rock"
                        },
                        new
                        {
                            Id = 20,
                            AlbumDestacado = "Ramones (1976)",
                            CancionDestacada = "Blitzkrieg Bop",
                            Imagen = "https://www.rockarchive.com/media/1491/the-ramones-ra001stwa.jpg",
                            Nombre = "Ramones",
                            Resena = "Pioneros del punk, despojaron el rock a su esencia más básica: tres acordes, velocidad y una energía cruda y contagiosa.",
                            Subgenero = "Punk Rock"
                        },
                        new
                        {
                            Id = 21,
                            AlbumDestacado = "Never Mind the Bollocks...",
                            CancionDestacada = "Anarchy in the U.K.",
                            Imagen = "https://www.rockarchive.com/media/1520/sex-pistols-sp001jf.jpg",
                            Nombre = "Sex Pistols",
                            Resena = "La banda que encarnó la furia y el nihilismo del punk británico. Su breve y caótica existencia dejó una marca indeleble en la música y la cultura.",
                            Subgenero = "Punk Rock"
                        },
                        new
                        {
                            Id = 22,
                            AlbumDestacado = "London Calling (1979)",
                            CancionDestacada = "London Calling",
                            Imagen = "https://www.rockarchive.com/media/1099/the-clash-cl001sh.jpg",
                            Nombre = "The Clash",
                            Resena = "Conocidos como 'la única banda que importa', fusionaron el punk con reggae, ska y rockabilly, abordando temas políticos y sociales.",
                            Subgenero = "Punk Rock / New Wave"
                        },
                        new
                        {
                            Id = 23,
                            AlbumDestacado = "The Joshua Tree (1987)",
                            CancionDestacada = "With or Without You",
                            Imagen = "https://www.rockarchive.com/media/1560/u2-ut007dc.jpg",
                            Nombre = "U2",
                            Resena = "Desde sus raíces post-punk, se convirtieron en una de las bandas más grandes del mundo, con el sonido de guitarra de The Edge y la voz apasionada de Bono.",
                            Subgenero = "Alternative Rock / Post-Punk"
                        },
                        new
                        {
                            Id = 24,
                            AlbumDestacado = "Appetite for Destruction (1987)",
                            CancionDestacada = "Sweet Child o' Mine",
                            Imagen = "https://ticketlive.com.co/wp-content/uploads/2025/05/1900x1900-000000-80-0-0-1024x1024.jpg",
                            Nombre = "Guns N' Roses",
                            Resena = "Irrumpieron en la escena de los 80 con una peligrosa mezcla de hard rock, punk y blues, personificando el exceso del rock de estadio.",
                            Subgenero = "Hard Rock"
                        },
                        new
                        {
                            Id = 25,
                            AlbumDestacado = "Born to Run (1975)",
                            CancionDestacada = "Born to Run",
                            Imagen = "https://faroutmagazine.co.uk/static/uploads/1/2024/03/Bruce-Springsteen-1980-Musician-Far-Out-Magazine-F.jpg",
                            Nombre = "Bruce Springsteen",
                            Resena = "Conocido como 'The Boss', sus canciones son crónicas de la vida de la clase trabajadora estadounidense, llenas de pasión y energía rockera.",
                            Subgenero = "Heartland Rock"
                        },
                        new
                        {
                            Id = 26,
                            AlbumDestacado = "Nevermind (1991)",
                            CancionDestacada = "Smells Like Teen Spirit",
                            Imagen = "https://static.wikia.nocookie.net/the-offspring/images/6/6e/Nirvana.jpg",
                            Nombre = "Nirvana",
                            Resena = "Lideraron la revolución del grunge, cambiando el panorama musical de los 90 con su sonido que alternaba entre la apatía y la furia.",
                            Subgenero = "Grunge / Alternative Rock"
                        },
                        new
                        {
                            Id = 27,
                            AlbumDestacado = "Ten (1991)",
                            CancionDestacada = "Alive",
                            Imagen = "https://www.cutawayguitarmagazine.com/wp-content/uploads/oldweb/art224-pearl-jam.jpg",
                            Nombre = "Pearl Jam",
                            Resena = "Una de las bandas más influyentes de la escena de Seattle, conocidos por la intensa voz de Eddie Vedder y su postura anti-corporativa.",
                            Subgenero = "Grunge / Alternative Rock"
                        },
                        new
                        {
                            Id = 28,
                            AlbumDestacado = "Automatic for the People (1992)",
                            CancionDestacada = "Losing My Religion",
                            Imagen = "https://m.media-amazon.com/images/M/MV5BYTE5ZGZjNmItNDI1Zi00OWM3LTg3NjAtOGZmOGRmOTJmMTIzXkEyXkFqcGc@._V1_.jpg",
                            Nombre = "R.E.M.",
                            Resena = "Pioneros del rock alternativo, su sonido jangle-pop y las enigmáticas letras de Michael Stipe los llevaron del underground a la fama mundial.",
                            Subgenero = "Alternative Rock"
                        },
                        new
                        {
                            Id = 29,
                            AlbumDestacado = "Californication (1999)",
                            CancionDestacada = "Under the Bridge",
                            Imagen = "https://cdn.artphotolimited.com/images/63c7c308bd40b81dba379fcc/1000x1000/red-hot-chili-peppers-france-2006.jpg",
                            Nombre = "Red Hot Chili Peppers",
                            Resena = "Fusionaron funk, punk y rock psicodélico para crear un sonido enérgico y distintivo, impulsado por la icónica línea de bajo de Flea.",
                            Subgenero = "Funk Rock / Alternative Rock"
                        },
                        new
                        {
                            Id = 30,
                            AlbumDestacado = "Master of Puppets (1986)",
                            CancionDestacada = "Master of Puppets",
                            Imagen = "https://images.lesindesradios.fr/fit-in/1100x2000/filters:format(webp)/radios/ouifm/importrk/2013/05/metallica-320x320.jpg",
                            Nombre = "Metallica",
                            Resena = "Una de las bandas de heavy metal más exitosas de la historia, definieron el thrash metal con su velocidad, agresividad y complejidad musical.",
                            Subgenero = "Thrash Metal"
                        },
                        new
                        {
                            Id = 31,
                            AlbumDestacado = "Synchronicity (1983)",
                            CancionDestacada = "Every Breath You Take",
                            Imagen = "https://poprockphotos.com/wp-content/uploads/2024/06/Police.-Stuart-Sting-Andy-.jpg",
                            Nombre = "The Police",
                            Resena = "Este trío británico mezcló rock con influencias de reggae y jazz, creando un sonido sofisticado y minimalista que dominó las radios de los 80.",
                            Subgenero = "New Wave / Post-Punk"
                        },
                        new
                        {
                            Id = 32,
                            AlbumDestacado = "Brothers in Arms (1985)",
                            CancionDestacada = "Sultans of Swing",
                            Imagen = "https://pyxis.nymag.com/v1/imgs/828/001/1506233306eb8a79512d07edce6a528d91-dire-straits-lede-2.rhorizontal.w700.jpg",
                            Nombre = "Dire Straits",
                            Resena = "Liderados por la inconfundible guitarra y voz de Mark Knopfler, su sonido limpio y melódico fue un contrapunto al punk y la new wave.",
                            Subgenero = "Blues Rock / Roots Rock"
                        },
                        new
                        {
                            Id = 33,
                            AlbumDestacado = "OK Computer (1997)",
                            CancionDestacada = "Paranoid Android",
                            Imagen = "https://prensarock.com/wp-content/uploads/2016/05/radiohead_2016.jpg",
                            Nombre = "Radiohead",
                            Resena = "Constantemente empujando los límites de la música rock, son conocidos por su experimentación sónica y sus temas de alienación moderna.",
                            Subgenero = "Alternative Rock / Art Rock"
                        },
                        new
                        {
                            Id = 34,
                            AlbumDestacado = "(What's the Story) Morning Glory? (1995)",
                            CancionDestacada = "Wonderwall",
                            Imagen = "https://inews.co.uk/wp-content/uploads/2024/08/SEI_218804151.jpg",
                            Nombre = "Oasis",
                            Resena = "La banda insignia del movimiento Britpop de los 90, con himnos de estadio y la volátil relación entre los hermanos Gallagher en su núcleo.",
                            Subgenero = "Britpop"
                        },
                        new
                        {
                            Id = 35,
                            AlbumDestacado = "The Queen Is Dead (1986)",
                            CancionDestacada = "There Is a Light That Never Goes Out",
                            Imagen = "https://standfirst-designweek-production.imgix.net/uploads/2013/07/The-Smiths.jpg",
                            Nombre = "The Smiths",
                            Resena = "Definieron el sonido del rock indie británico de los 80 con las guitarras de Johnny Marr y las melancólicas letras de Morrissey.",
                            Subgenero = "Jangle Pop / Indie Rock"
                        },
                        new
                        {
                            Id = 36,
                            AlbumDestacado = "Disintegration (1989)",
                            CancionDestacada = "Just Like Heaven",
                            Imagen = "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/3a/The_Cure.jpg",
                            Nombre = "The Cure",
                            Resena = "Liderados por Robert Smith, transitaron del post-punk a un pop melancólico y atmosférico, convirtiéndose en íconos del rock gótico.",
                            Subgenero = "Gothic Rock / New Wave"
                        },
                        new
                        {
                            Id = 37,
                            AlbumDestacado = "Superunknown (1994)",
                            CancionDestacada = "Black Hole Sun",
                            Imagen = "https://marvel-b1-cdn.bc0a.com/f00000000293000/rockhall.com/wp-content/uploads/2024/04/Soundgarden_Square.jpg",
                            Nombre = "Soundgarden",
                            Resena = "Una de las bandas pilares del grunge, destacaron por su complejidad técnica y la increíble potencia vocal de Chris Cornell.",
                            Subgenero = "Grunge / Hard Rock"
                        },
                        new
                        {
                            Id = 38,
                            AlbumDestacado = "The Colour and the Shape (1997)",
                            CancionDestacada = "Everlong",
                            Imagen = "https://static01.nyt.com/images/2021/02/07/arts/07foo-fighters1/07foo-fighters1-mediumSquareAt3X-v2.jpg",
                            Nombre = "Foo Fighters",
                            Resena = "Nacidos de las cenizas de Nirvana, la banda de Dave Grohl se convirtió en un pilar del rock de estadio con himnos enérgicos y melódicos.",
                            Subgenero = "Alternative Rock / Post-Grunge"
                        },
                        new
                        {
                            Id = 39,
                            AlbumDestacado = "Dookie (1994)",
                            CancionDestacada = "Basket Case",
                            Imagen = "https://img.apmcdn.org/36722792e54dca8b68980f80b2fd3503bc3ca0d4/square/5ced62-20240129-green-day-2000.jpg",
                            Nombre = "Green Day",
                            Resena = "Llevaron el pop-punk al mainstream con melodías pegadizas y una energía juvenil que revitalizó el género en los años 90.",
                            Subgenero = "Pop Punk / Punk Rock"
                        },
                        new
                        {
                            Id = 40,
                            AlbumDestacado = "Is This It (2001)",
                            CancionDestacada = "Last Nite",
                            Imagen = "https://static01.nyt.com/images/2020/04/16/arts/13strokes-review1/13strokes-review1-mediumSquareAt3X.jpg",
                            Nombre = "The Strokes",
                            Resena = "Lideraron el resurgimiento del garage rock a principios de los 2000 con un sonido cool, minimalista y lleno de guitarras angulares.",
                            Subgenero = "Indie Rock / Garage Rock Revival"
                        },
                        new
                        {
                            Id = 41,
                            AlbumDestacado = "Elephant (2003)",
                            CancionDestacada = "Seven Nation Army",
                            Imagen = "https://www.rollingstone.com/wp-content/uploads/2020/06/the-white-stripes.jpg",
                            Nombre = "The White Stripes",
                            Resena = "Este dúo de Detroit revitalizó el blues y el garage rock con un enfoque minimalista pero potente: solo guitarra y batería.",
                            Subgenero = "Garage Rock / Blues Rock"
                        },
                        new
                        {
                            Id = 42,
                            AlbumDestacado = "Whatever People Say I Am...",
                            CancionDestacada = "I Bet You Look Good on the Dancefloor",
                            Imagen = "http://www.mxdwn.co.uk/wp-content/uploads/2013/07/2013-glastonbury-festival-guide-previews-hints-tips-and-advice_arctic-monkeys_1000PxSq72Dpi.jpeg",
                            Nombre = "Arctic Monkeys",
                            Resena = "Fueron una de las primeras bandas en saltar a la fama gracias a internet, con letras ingeniosas sobre la vida nocturna juvenil y riffs de guitarra frenéticos.",
                            Subgenero = "Indie Rock / Post-Punk Revival"
                        },
                        new
                        {
                            Id = 43,
                            AlbumDestacado = "Only by the Night (2008)",
                            CancionDestacada = "Sex on Fire",
                            Imagen = "https://www.billboard.com/wp-content/uploads/media/Kings-Of-Leon-perform-Nashville-2016-billboard-1548.jpg",
                            Nombre = "Kings of Leon",
                            Resena = "Evolucionaron de un rock sureño y crudo a un sonido de rock de estadio pulido que les otorgó fama mundial a finales de los 2000.",
                            Subgenero = "Alternative Rock"
                        },
                        new
                        {
                            Id = 44,
                            AlbumDestacado = "Hybrid Theory (2000)",
                            CancionDestacada = "In the End",
                            Imagen = "https://www.watchmojo.com/uploads/thumbs720/M-RR-Linkin-Park-480i60.jpg",
                            Nombre = "Linkin Park",
                            Resena = "Definieron el sonido nu-metal de los 2000 al fusionar rock, hip-hop y electrónica, con letras que conectaron con una generación de jóvenes.",
                            Subgenero = "Nu Metal / Alternative Rock"
                        },
                        new
                        {
                            Id = 45,
                            AlbumDestacado = "Absolution (2003)",
                            CancionDestacada = "Hysteria",
                            Imagen = "https://media.npr.org/assets/img/2012/08/09/muse_custom-8180cf681271b8fd07c5fc4d6f4ed4e48a055fc6.jpg?s=1100&c=50&f=jpeg",
                            Nombre = "Muse",
                            Resena = "Este trío británico es conocido por su sonido grandilocuente, que mezcla rock alternativo con ópera, electrónica y temas conspiranoicos.",
                            Subgenero = "Alternative Rock / Space Rock"
                        },
                        new
                        {
                            Id = 46,
                            AlbumDestacado = "A Rush of Blood to the Head (2002)",
                            CancionDestacada = "Clocks",
                            Imagen = "https://tsmnoticias.com/wp-content/uploads/2015/11/Coldplay-confirma-concierto-en-Colombia.jpg",
                            Nombre = "Coldplay",
                            Resena = "Desde sus inicios en el rock alternativo melódico, se han convertido en una de las bandas de pop-rock más grandes del planeta.",
                            Subgenero = "Alternative Rock / Pop Rock"
                        },
                        new
                        {
                            Id = 47,
                            AlbumDestacado = "Full Moon Fever (1989)",
                            CancionDestacada = "Free Fallin'",
                            Imagen = "https://compote.slate.com/images/0c8bffda-b045-47de-9899-df091904c5a8.jpeg",
                            Nombre = "Tom Petty",
                            Resena = "Un maestro de la composición de canciones, Tom Petty creó un rock clásico y atemporal, con melodías que se sienten instantáneamente familiares.",
                            Subgenero = "Heartland Rock"
                        },
                        new
                        {
                            Id = 48,
                            AlbumDestacado = "Pearl (1971)",
                            CancionDestacada = "Me and Bobby McGee",
                            Imagen = "https://cdn.prod.website-files.com/65c3e2124e0ae36491eed349/65c3e2124e0ae36491eef56a_janis-joplin-lentes.jpeg",
                            Nombre = "Janis Joplin",
                            Resena = "Con una voz cruda, poderosa y llena de emoción, Janis Joplin fue una de las cantantes de rock y blues más icónicas de su era.",
                            Subgenero = "Blues Rock"
                        },
                        new
                        {
                            Id = 49,
                            AlbumDestacado = "(Pronounced 'Lĕh-'nérd 'Skin-'nérd')",
                            CancionDestacada = "Sweet Home Alabama",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/9/9c/Lynyrd_Skynyrd_%281977%29.jpg",
                            Nombre = "Lynyrd Skynyrd",
                            Resena = "La banda por excelencia del rock sureño, conocidos por su triple ataque de guitarras y por himnos que definieron el género.",
                            Subgenero = "Southern Rock"
                        },
                        new
                        {
                            Id = 50,
                            AlbumDestacado = "Parallel Lines (1978)",
                            CancionDestacada = "Heart of Glass",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Blondie1977.jpg/1200px-Blondie1977.jpg",
                            Nombre = "Blondie",
                            Resena = "Surgidos de la escena punk de Nueva York, Blondie y la icónica Debbie Harry fusionaron punk, disco y pop para dominar las listas de éxitos.",
                            Subgenero = "New Wave / Punk Rock"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
