// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RockProjectBackend.Data;

#nullable disable

namespace RockProjectBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250627192710_SeedArtistsData")]
    partial class SeedArtistsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RockProjectBackend.Models.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlbumDestacado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CancionDestacada")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Resena")
                        .HasColumnType("text");

                    b.Property<string>("Subgenero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Artistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumDestacado = "Elvis Presley (1956)",
                            CancionDestacada = "Hound Dog",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/9/99/Elvis_Presley_promoting_Jailhouse_Rock.jpg",
                            Nombre = "Elvis Presley",
                            Resena = "Considerado el 'Rey del Rock and Roll', su carisma y su fusión de country con rhythm and blues lo convirtieron en un ícono cultural que cambió la música para siempre.",
                            Subgenero = "Rockabilly / Rock and Roll"
                        },
                        new
                        {
                            Id = 2,
                            AlbumDestacado = "Chuck Berry Is on Top (1959)",
                            CancionDestacada = "Johnny B. Goode",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/6/63/Chuck_Berry_in_1957.jpg",
                            Nombre = "Chuck Berry",
                            Resena = "Uno de los padres fundadores del rock, definió su sonido con su distintiva guitarra y letras que capturaban el espíritu de la juventud estadounidense.",
                            Subgenero = "Rock and Roll"
                        },
                        new
                        {
                            Id = 3,
                            AlbumDestacado = "Here's Little Richard (1957)",
                            CancionDestacada = "Tutti Frutti",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/5/56/Little_Richard_1965.jpg",
                            Nombre = "Little Richard",
                            Resena = "Con su energía explosiva, su piano frenético y su voz inconfundible, fue una fuerza pionera que inyectó extravagancia y dinamismo al rock and roll.",
                            Subgenero = "Rock and Roll"
                        },
                        new
                        {
                            Id = 4,
                            AlbumDestacado = "The 'Chirping' Crickets (1957)",
                            CancionDestacada = "Peggy Sue",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/c/cd/Buddy_Holly_in_1958.jpg",
                            Nombre = "Buddy Holly",
                            Resena = "Un innovador compositor y guitarrista cuya carrera, aunque breve, influyó profundamente en la estructura de la música pop y el formato de las bandas de rock.",
                            Subgenero = "Rockabilly"
                        },
                        new
                        {
                            Id = 5,
                            AlbumDestacado = "Sgt. Pepper's Lonely Hearts Club Band (1967)",
                            CancionDestacada = "A Day in the Life",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/d/df/The_Fabs.JPG",
                            Nombre = "The Beatles",
                            Resena = "Originarios de Liverpool, los 'Fab Four' revolucionaron la música popular con su innovadora composición, armonías vocales y experimentación en el estudio.",
                            Subgenero = "Rock Psicodélico / Pop Rock"
                        },
                        new
                        {
                            Id = 6,
                            AlbumDestacado = "Exile on Main St. (1972)",
                            CancionDestacada = "(I Can't Get No) Satisfaction",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/7/78/The_Rolling_Stones_in_1965.jpg",
                            Nombre = "The Rolling Stones",
                            Resena = "La encarnación de la rebeldía del rock, con un sonido crudo basado en el blues y una actitud que los ha mantenido como una de las bandas más grandes durante décadas.",
                            Subgenero = "Blues Rock / Rock and Roll"
                        },
                        new
                        {
                            Id = 7,
                            AlbumDestacado = "Who's Next (1971)",
                            CancionDestacada = "Baba O'Riley",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/f/f7/The_Who_1975.jpg",
                            Nombre = "The Who",
                            Resena = "Conocidos por sus óperas rock y sus explosivas actuaciones en vivo, The Who empujó los límites del sonido y la narrativa en la música rock.",
                            Subgenero = "Hard Rock / Rock"
                        },
                        new
                        {
                            Id = 8,
                            AlbumDestacado = "Led Zeppelin IV (1971)",
                            CancionDestacada = "Stairway to Heaven",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/4/4f/Led_Zeppelin_-_1975.jpg",
                            Nombre = "Led Zeppelin",
                            Resena = "Pioneros del hard rock y el heavy metal, esta banda británica es célebre por sus poderosos riffs de guitarra y su épica musicalidad.",
                            Subgenero = "Hard Rock / Folk Rock"
                        },
                        new
                        {
                            Id = 9,
                            AlbumDestacado = "The Dark Side of the Moon (1973)",
                            CancionDestacada = "Money",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/d/d6/Pink_Floyd_-_all_members.jpg",
                            Nombre = "Pink Floyd",
                            Resena = "Maestros del rock progresivo y psicodélico, son conocidos por sus álbumes conceptuales, letras filosóficas y espectáculos en vivo elaborados.",
                            Subgenero = "Rock Progresivo / Psicodélico"
                        },
                        new
                        {
                            Id = 10,
                            AlbumDestacado = "Are You Experienced (1967)",
                            CancionDestacada = "Purple Haze",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/a/ae/Jimi_Hendrix_1967.png",
                            Nombre = "Jimi Hendrix",
                            Resena = "Considerado el guitarrista más influyente de la historia, redefinió las posibilidades del instrumento con su técnica innovadora y su uso de la distorsión y el feedback.",
                            Subgenero = "Rock Psicodélico / Hard Rock"
                        },
                        new
                        {
                            Id = 11,
                            AlbumDestacado = "A Night at the Opera (1975)",
                            CancionDestacada = "Bohemian Rhapsody",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/3/33/Queen_in_1977.jpg",
                            Nombre = "Queen",
                            Resena = "Liderados por el incomparable Freddie Mercury, fusionaron el glam, el hard rock y la ópera para crear un sonido grandilocuente y único.",
                            Subgenero = "Glam Rock / Hard Rock"
                        },
                        new
                        {
                            Id = 12,
                            AlbumDestacado = "The Rise and Fall of Ziggy Stardust...",
                            CancionDestacada = "Heroes",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/e/e8/David-Bowie_Chicago_2002-08-08_cropped.jpg",
                            Nombre = "David Bowie",
                            Resena = "Un camaleón musical y cultural, Bowie constantemente reinventó su imagen y sonido, explorando géneros desde el glam hasta la electrónica.",
                            Subgenero = "Glam Rock / Art Rock"
                        },
                        new
                        {
                            Id = 13,
                            AlbumDestacado = "Highway 61 Revisited (1965)",
                            CancionDestacada = "Like a Rolling Stone",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/0/02/Bob_Dylan_-_Azkena_Rock_Festival_2010_1.jpg",
                            Nombre = "Bob Dylan",
                            Resena = "La voz de una generación, sus poéticas y socialmente conscientes letras transformaron la música folk y la elevaron a una forma de arte literario.",
                            Subgenero = "Folk Rock"
                        },
                        new
                        {
                            Id = 14,
                            AlbumDestacado = "The Doors (1967)",
                            CancionDestacada = "Light My Fire",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/7/79/The_Doors_1968.jpg",
                            Nombre = "The Doors",
                            Resena = "Con la poesía oscura de Jim Morrison y el sonido hipnótico de sus teclados, The Doors exploró los rincones más oscuros de la psique humana.",
                            Subgenero = "Rock Psicodélico"
                        },
                        new
                        {
                            Id = 15,
                            AlbumDestacado = "Cosmo's Factory (1970)",
                            CancionDestacada = "Fortunate Son",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/3/3e/Creedence_Clearwater_Revival_1968.jpg",
                            Nombre = "Creedence Clearwater Revival",
                            Resena = "Liderados por John Fogerty, crearon un sonido distintivo de rock sureño con éxitos concisos y potentes que se convirtieron en himnos.",
                            Subgenero = "Swamp Rock / Roots Rock"
                        },
                        new
                        {
                            Id = 16,
                            AlbumDestacado = "Paranoid (1970)",
                            CancionDestacada = "Paranoid",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/8/87/Black_Sabbath_1970.jpg",
                            Nombre = "Black Sabbath",
                            Resena = "Considerados los creadores del heavy metal, sus riffs oscuros y pesados, cortesía de Tony Iommi, sentaron las bases para todo un género.",
                            Subgenero = "Heavy Metal / Hard Rock"
                        },
                        new
                        {
                            Id = 17,
                            AlbumDestacado = "Back in Black (1980)",
                            CancionDestacada = "Back in Black",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/9/91/ACDC_in_2001.jpg",
                            Nombre = "AC/DC",
                            Resena = "La personificación del rock and roll directo y sin concesiones. Su música se basa en riffs de guitarra simples, potentes y memorables.",
                            Subgenero = "Hard Rock"
                        },
                        new
                        {
                            Id = 18,
                            AlbumDestacado = "Hotel California (1976)",
                            CancionDestacada = "Hotel California",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/b/b5/Eagles_band_on_tour.jpg",
                            Nombre = "Eagles",
                            Resena = "Maestros de las armonías vocales y del sonido californiano, mezclaron el country con el soft rock para crear algunas de las canciones más vendidas de la historia.",
                            Subgenero = "Soft Rock / Country Rock"
                        },
                        new
                        {
                            Id = 19,
                            AlbumDestacado = "Rumours (1977)",
                            CancionDestacada = "Go Your Own Way",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/f/fe/Fleetwood_Mac_Billboard_1977.jpg",
                            Nombre = "Fleetwood Mac",
                            Resena = "Con una mezcla única de talento británico y estadounidense, crearon pop-rock sofisticado, marcado por sus complejas relaciones internas.",
                            Subgenero = "Soft Rock / Pop Rock"
                        },
                        new
                        {
                            Id = 20,
                            AlbumDestacado = "Ramones (1976)",
                            CancionDestacada = "Blitzkrieg Bop",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/6/6b/Ramones_in_Tivoli_Stockholm_1977.jpg",
                            Nombre = "Ramones",
                            Resena = "Pioneros del punk, despojaron el rock a su esencia más básica: tres acordes, velocidad y una energía cruda y contagiosa.",
                            Subgenero = "Punk Rock"
                        },
                        new
                        {
                            Id = 21,
                            AlbumDestacado = "Never Mind the Bollocks...",
                            CancionDestacada = "Anarchy in the U.K.",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/f/ff/Sex_Pistols-publicity-shot-1977.jpg",
                            Nombre = "Sex Pistols",
                            Resena = "La banda que encarnó la furia y el nihilismo del punk británico. Su breve y caótica existencia dejó una marca indeleble en la música y la cultura.",
                            Subgenero = "Punk Rock"
                        },
                        new
                        {
                            Id = 22,
                            AlbumDestacado = "London Calling (1979)",
                            CancionDestacada = "London Calling",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/0/07/The_Clash_at_the_Lochem_Festival_1982.jpg",
                            Nombre = "The Clash",
                            Resena = "Conocidos como 'la única banda que importa', fusionaron el punk con reggae, ska y rockabilly, abordando temas políticos y sociales.",
                            Subgenero = "Punk Rock / New Wave"
                        },
                        new
                        {
                            Id = 23,
                            AlbumDestacado = "The Joshua Tree (1987)",
                            CancionDestacada = "With or Without You",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/b/b5/U2_in_2017.jpg",
                            Nombre = "U2",
                            Resena = "Desde sus raíces post-punk, se convirtieron en una de las bandas más grandes del mundo, con el sonido de guitarra de The Edge y la voz apasionada de Bono.",
                            Subgenero = "Alternative Rock / Post-Punk"
                        },
                        new
                        {
                            Id = 24,
                            AlbumDestacado = "Appetite for Destruction (1987)",
                            CancionDestacada = "Sweet Child o' Mine",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/3/3b/Guns_N%27_Roses_at_The_O2_Arena_-_2012_%282%29.jpg",
                            Nombre = "Guns N' Roses",
                            Resena = "Irrumpieron en la escena de los 80 con una peligrosa mezcla de hard rock, punk y blues, personificando el exceso del rock de estadio.",
                            Subgenero = "Hard Rock"
                        },
                        new
                        {
                            Id = 25,
                            AlbumDestacado = "Born to Run (1975)",
                            CancionDestacada = "Born to Run",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/f/f4/Bruce_Springsteen_-_Roskilde_Festival_2012.jpg",
                            Nombre = "Bruce Springsteen",
                            Resena = "Conocido como 'The Boss', sus canciones son crónicas de la vida de la clase trabajadora estadounidense, llenas de pasión y energía rockera.",
                            Subgenero = "Heartland Rock"
                        },
                        new
                        {
                            Id = 26,
                            AlbumDestacado = "Nevermind (1991)",
                            CancionDestacada = "Smells Like Teen Spirit",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/1/19/Nirvana_around_1992.jpg",
                            Nombre = "Nirvana",
                            Resena = "Lideraron la revolución del grunge, cambiando el panorama musical de los 90 con su sonido que alternaba entre la apatía y la furia.",
                            Subgenero = "Grunge / Alternative Rock"
                        },
                        new
                        {
                            Id = 27,
                            AlbumDestacado = "Ten (1991)",
                            CancionDestacada = "Alive",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/5/5e/Pearl_Jam_in_2009.jpg",
                            Nombre = "Pearl Jam",
                            Resena = "Una de las bandas más influyentes de la escena de Seattle, conocidos por la intensa voz de Eddie Vedder y su postura anti-corporativa.",
                            Subgenero = "Grunge / Alternative Rock"
                        },
                        new
                        {
                            Id = 28,
                            AlbumDestacado = "Automatic for the People (1992)",
                            CancionDestacada = "Losing My Religion",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/b/b0/R.E.M._Press_Conference_in_Mexico_City.jpg",
                            Nombre = "R.E.M.",
                            Resena = "Pioneros del rock alternativo, su sonido jangle-pop y las enigmáticas letras de Michael Stipe los llevaron del underground a la fama mundial.",
                            Subgenero = "Alternative Rock"
                        },
                        new
                        {
                            Id = 29,
                            AlbumDestacado = "Californication (1999)",
                            CancionDestacada = "Under the Bridge",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/8/89/Red_Hot_Chili_Peppers_2012-08-26_Rock_en_Seine_01.jpg",
                            Nombre = "Red Hot Chili Peppers",
                            Resena = "Fusionaron funk, punk y rock psicodélico para crear un sonido enérgico y distintivo, impulsado por la icónica línea de bajo de Flea.",
                            Subgenero = "Funk Rock / Alternative Rock"
                        },
                        new
                        {
                            Id = 30,
                            AlbumDestacado = "Master of Puppets (1986)",
                            CancionDestacada = "Master of Puppets",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/b/b7/Metallica_at_The_O2_Arena_London_2008.jpg",
                            Nombre = "Metallica",
                            Resena = "Una de las bandas de heavy metal más exitosas de la historia, definieron el thrash metal con su velocidad, agresividad y complejidad musical.",
                            Subgenero = "Thrash Metal"
                        },
                        new
                        {
                            Id = 31,
                            AlbumDestacado = "Synchronicity (1983)",
                            CancionDestacada = "Every Breath You Take",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/a/a4/The_Police_in_concert_in_1981_-_2.jpg",
                            Nombre = "The Police",
                            Resena = "Este trío británico mezcló rock con influencias de reggae y jazz, creando un sonido sofisticado y minimalista que dominó las radios de los 80.",
                            Subgenero = "New Wave / Post-Punk"
                        },
                        new
                        {
                            Id = 32,
                            AlbumDestacado = "Brothers in Arms (1985)",
                            CancionDestacada = "Sultans of Swing",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/4/4b/Dire_Straits_-_Hammersmith_Odeon_1979_03.jpg",
                            Nombre = "Dire Straits",
                            Resena = "Liderados por la inconfundible guitarra y voz de Mark Knopfler, su sonido limpio y melódico fue un contrapunto al punk y la new wave.",
                            Subgenero = "Blues Rock / Roots Rock"
                        },
                        new
                        {
                            Id = 33,
                            AlbumDestacado = "OK Computer (1997)",
                            CancionDestacada = "Paranoid Android",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/2/22/Radiohead_Coachella_2017.jpg",
                            Nombre = "Radiohead",
                            Resena = "Constantemente empujando los límites de la música rock, son conocidos por su experimentación sónica y sus temas de alienación moderna.",
                            Subgenero = "Alternative Rock / Art Rock"
                        },
                        new
                        {
                            Id = 34,
                            AlbumDestacado = "(What's the Story) Morning Glory? (1995)",
                            CancionDestacada = "Wonderwall",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/f/fb/Oasis_2008.jpg",
                            Nombre = "Oasis",
                            Resena = "La banda insignia del movimiento Britpop de los 90, con himnos de estadio y la volátil relación entre los hermanos Gallagher en su núcleo.",
                            Subgenero = "Britpop"
                        },
                        new
                        {
                            Id = 35,
                            AlbumDestacado = "The Queen Is Dead (1986)",
                            CancionDestacada = "There Is a Light That Never Goes Out",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/2/29/The_Smiths_promo_photo.jpg",
                            Nombre = "The Smiths",
                            Resena = "Definieron el sonido del rock indie británico de los 80 con las guitarras de Johnny Marr y las melancólicas letras de Morrissey.",
                            Subgenero = "Jangle Pop / Indie Rock"
                        },
                        new
                        {
                            Id = 36,
                            AlbumDestacado = "Disintegration (1989)",
                            CancionDestacada = "Just Like Heaven",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/8/87/The_Cure_in_2016.jpg",
                            Nombre = "The Cure",
                            Resena = "Liderados por Robert Smith, transitaron del post-punk a un pop melancólico y atmosférico, convirtiéndose en íconos del rock gótico.",
                            Subgenero = "Gothic Rock / New Wave"
                        },
                        new
                        {
                            Id = 37,
                            AlbumDestacado = "Superunknown (1994)",
                            CancionDestacada = "Black Hole Sun",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/e/e5/Soundgarden_Rock_am_Ring_2012.jpg",
                            Nombre = "Soundgarden",
                            Resena = "Una de las bandas pilares del grunge, destacaron por su complejidad técnica y la increíble potencia vocal de Chris Cornell.",
                            Subgenero = "Grunge / Hard Rock"
                        },
                        new
                        {
                            Id = 38,
                            AlbumDestacado = "The Colour and the Shape (1997)",
                            CancionDestacada = "Everlong",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/d/d4/Foo_Fighters_at_Lollapalooza_Chile_2012.jpg",
                            Nombre = "Foo Fighters",
                            Resena = "Nacidos de las cenizas de Nirvana, la banda de Dave Grohl se convirtió en un pilar del rock de estadio con himnos enérgicos y melódicos.",
                            Subgenero = "Alternative Rock / Post-Grunge"
                        },
                        new
                        {
                            Id = 39,
                            AlbumDestacado = "Dookie (1994)",
                            CancionDestacada = "Basket Case",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/8/89/Green_Day_-_d.jpg",
                            Nombre = "Green Day",
                            Resena = "Llevaron el pop-punk al mainstream con melodías pegadizas y una energía juvenil que revitalizó el género en los años 90.",
                            Subgenero = "Pop Punk / Punk Rock"
                        },
                        new
                        {
                            Id = 40,
                            AlbumDestacado = "Is This It (2001)",
                            CancionDestacada = "Last Nite",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/7/7b/The_Strokes_2006.jpg",
                            Nombre = "The Strokes",
                            Resena = "Lideraron el resurgimiento del garage rock a principios de los 2000 con un sonido cool, minimalista y lleno de guitarras angulares.",
                            Subgenero = "Indie Rock / Garage Rock Revival"
                        },
                        new
                        {
                            Id = 41,
                            AlbumDestacado = "Elephant (2003)",
                            CancionDestacada = "Seven Nation Army",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/d/d7/The_White_Stripes_live_at_the_O2_Wireless_Festival_2007.jpg",
                            Nombre = "The White Stripes",
                            Resena = "Este dúo de Detroit revitalizó el blues y el garage rock con un enfoque minimalista pero potente: solo guitarra y batería.",
                            Subgenero = "Garage Rock / Blues Rock"
                        },
                        new
                        {
                            Id = 42,
                            AlbumDestacado = "Whatever People Say I Am...",
                            CancionDestacada = "I Bet You Look Good on the Dancefloor",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/0/08/Arctic_Monkeys_at_The_O2_Arena_%282013%29.jpg",
                            Nombre = "Arctic Monkeys",
                            Resena = "Fueron una de las primeras bandas en saltar a la fama gracias a internet, con letras ingeniosas sobre la vida nocturna juvenil y riffs de guitarra frenéticos.",
                            Subgenero = "Indie Rock / Post-Punk Revival"
                        },
                        new
                        {
                            Id = 43,
                            AlbumDestacado = "Only by the Night (2008)",
                            CancionDestacada = "Sex on Fire",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/d/d3/Kings_of_Leon_at_the_O2_Arena%2C_2013_%283%29.jpg",
                            Nombre = "Kings of Leon",
                            Resena = "Evolucionaron de un rock sureño y crudo a un sonido de rock de estadio pulido que les otorgó fama mundial a finales de los 2000.",
                            Subgenero = "Alternative Rock"
                        },
                        new
                        {
                            Id = 44,
                            AlbumDestacado = "Hybrid Theory (2000)",
                            CancionDestacada = "In the End",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/9/9f/Linkin_park_2010.jpg",
                            Nombre = "Linkin Park",
                            Resena = "Definieron el sonido nu-metal de los 2000 al fusionar rock, hip-hop y electrónica, con letras que conectaron con una generación de jóvenes.",
                            Subgenero = "Nu Metal / Alternative Rock"
                        },
                        new
                        {
                            Id = 45,
                            AlbumDestacado = "Absolution (2003)",
                            CancionDestacada = "Hysteria",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/9/91/Muse_in_2010.jpg",
                            Nombre = "Muse",
                            Resena = "Este trío británico es conocido por su sonido grandilocuente, que mezcla rock alternativo con ópera, electrónica y temas conspiranoicos.",
                            Subgenero = "Alternative Rock / Space Rock"
                        },
                        new
                        {
                            Id = 46,
                            AlbumDestacado = "A Rush of Blood to the Head (2002)",
                            CancionDestacada = "Clocks",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/7/73/Coldplay_live_at_the_Rock_im_Park_2011.jpg",
                            Nombre = "Coldplay",
                            Resena = "Desde sus inicios en el rock alternativo melódico, se han convertido en una de las bandas de pop-rock más grandes del planeta.",
                            Subgenero = "Alternative Rock / Pop Rock"
                        },
                        new
                        {
                            Id = 47,
                            AlbumDestacado = "Full Moon Fever (1989)",
                            CancionDestacada = "Free Fallin'",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/b/b5/Tom_Petty_and_the_Heartbreakers_in_2012.jpg",
                            Nombre = "Tom Petty",
                            Resena = "Un maestro de la composición de canciones, Tom Petty creó un rock clásico y atemporal, con melodías que se sienten instantáneamente familiares.",
                            Subgenero = "Heartland Rock"
                        },
                        new
                        {
                            Id = 48,
                            AlbumDestacado = "Pearl (1971)",
                            CancionDestacada = "Me and Bobby McGee",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/9/98/Janis_Joplin_in_1969_%28cropped%29.jpg",
                            Nombre = "Janis Joplin",
                            Resena = "Con una voz cruda, poderosa y llena de emoción, Janis Joplin fue una de las cantantes de rock y blues más icónicas de su era.",
                            Subgenero = "Blues Rock"
                        },
                        new
                        {
                            Id = 49,
                            AlbumDestacado = "(Pronounced 'Lĕh-'nérd 'Skin-'nérd')",
                            CancionDestacada = "Sweet Home Alabama",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/b/b3/Lynyrd_Skynyrd_-_Cobo_Hall.jpg",
                            Nombre = "Lynyrd Skynyrd",
                            Resena = "La banda por excelencia del rock sureño, conocidos por su triple ataque de guitarras y por himnos que definieron el género.",
                            Subgenero = "Southern Rock"
                        },
                        new
                        {
                            Id = 50,
                            AlbumDestacado = "Parallel Lines (1978)",
                            CancionDestacada = "Heart of Glass",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/a/a6/Blondie_-_1977.jpg",
                            Nombre = "Blondie",
                            Resena = "Surgidos de la escena punk de Nueva York, Blondie y la icónica Debbie Harry fusionaron punk, disco y pop para dominar las listas de éxitos.",
                            Subgenero = "New Wave / Punk Rock"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
