using Microsoft.EntityFrameworkCore;
using RockProjectBackend.Models;

namespace RockProjectBackend.Data
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
        }

        public DbSet<Artista> Artistas { get; set; }

        // Dentro de tu clase AppDbContext.cs
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Artista>().HasData(
                new Artista { Id = 1, Nombre = "Elvis Presley", AlbumDestacado = "Elvis Presley (1956)", CancionDestacada = "Hound Dog", Subgenero = "Rockabilly / Rock and Roll", Resena = "Considerado el 'Rey del Rock and Roll', su carisma y su fusión de country con rhythm and blues lo convirtieron en un ícono cultural que cambió la música para siempre.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/9/99/Elvis_Presley_promoting_Jailhouse_Rock.jpg" },
                new Artista { Id = 2, Nombre = "Chuck Berry", AlbumDestacado = "Chuck Berry Is on Top (1959)", CancionDestacada = "Johnny B. Goode", Subgenero = "Rock and Roll", Resena = "Uno de los padres fundadores del rock, definió su sonido con su distintiva guitarra y letras que capturaban el espíritu de la juventud estadounidense.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/6/63/Chuck_Berry_in_1957.jpg" },
                new Artista { Id = 3, Nombre = "Little Richard", AlbumDestacado = "Here's Little Richard (1957)", CancionDestacada = "Tutti Frutti", Subgenero = "Rock and Roll", Resena = "Con su energía explosiva, su piano frenético y su voz inconfundible, fue una fuerza pionera que inyectó extravagancia y dinamismo al rock and roll.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/5/56/Little_Richard_1965.jpg" },
                new Artista { Id = 4, Nombre = "Buddy Holly", AlbumDestacado = "The 'Chirping' Crickets (1957)", CancionDestacada = "Peggy Sue", Subgenero = "Rockabilly", Resena = "Un innovador compositor y guitarrista cuya carrera, aunque breve, influyó profundamente en la estructura de la música pop y el formato de las bandas de rock.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/c/cd/Buddy_Holly_in_1958.jpg" },
                new Artista { Id = 5, Nombre = "The Beatles", AlbumDestacado = "Sgt. Pepper's Lonely Hearts Club Band (1967)", CancionDestacada = "A Day in the Life", Subgenero = "Rock Psicodélico / Pop Rock", Resena = "Originarios de Liverpool, los 'Fab Four' revolucionaron la música popular con su innovadora composición, armonías vocales y experimentación en el estudio.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/d/df/The_Fabs.JPG" },
                new Artista { Id = 6, Nombre = "The Rolling Stones", AlbumDestacado = "Exile on Main St. (1972)", CancionDestacada = "(I Can't Get No) Satisfaction", Subgenero = "Blues Rock / Rock and Roll", Resena = "La encarnación de la rebeldía del rock, con un sonido crudo basado en el blues y una actitud que los ha mantenido como una de las bandas más grandes durante décadas.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/7/78/The_Rolling_Stones_in_1965.jpg" },
                new Artista { Id = 7, Nombre = "The Who", AlbumDestacado = "Who's Next (1971)", CancionDestacada = "Baba O'Riley", Subgenero = "Hard Rock / Rock", Resena = "Conocidos por sus óperas rock y sus explosivas actuaciones en vivo, The Who empujó los límites del sonido y la narrativa en la música rock.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/f/f7/The_Who_1975.jpg" },
                new Artista { Id = 8, Nombre = "Led Zeppelin", AlbumDestacado = "Led Zeppelin IV (1971)", CancionDestacada = "Stairway to Heaven", Subgenero = "Hard Rock / Folk Rock", Resena = "Pioneros del hard rock y el heavy metal, esta banda británica es célebre por sus poderosos riffs de guitarra y su épica musicalidad.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/4/4f/Led_Zeppelin_-_1975.jpg" },
                new Artista { Id = 9, Nombre = "Pink Floyd", AlbumDestacado = "The Dark Side of the Moon (1973)", CancionDestacada = "Money", Subgenero = "Rock Progresivo / Psicodélico", Resena = "Maestros del rock progresivo y psicodélico, son conocidos por sus álbumes conceptuales, letras filosóficas y espectáculos en vivo elaborados.", Imagen = "https://upload.wikimedia.org/wikipedia/en/d/d6/Pink_Floyd_-_all_members.jpg" },
                new Artista { Id = 10, Nombre = "Jimi Hendrix", AlbumDestacado = "Are You Experienced (1967)", CancionDestacada = "Purple Haze", Subgenero = "Rock Psicodélico / Hard Rock", Resena = "Considerado el guitarrista más influyente de la historia, redefinió las posibilidades del instrumento con su técnica innovadora y su uso de la distorsión y el feedback.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/a/ae/Jimi_Hendrix_1967.png" },
                new Artista { Id = 11, Nombre = "Queen", AlbumDestacado = "A Night at the Opera (1975)", CancionDestacada = "Bohemian Rhapsody", Subgenero = "Glam Rock / Hard Rock", Resena = "Liderados por el incomparable Freddie Mercury, fusionaron el glam, el hard rock y la ópera para crear un sonido grandilocuente y único.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/3/33/Queen_in_1977.jpg" },
                new Artista { Id = 12, Nombre = "David Bowie", AlbumDestacado = "The Rise and Fall of Ziggy Stardust...", CancionDestacada = "Heroes", Subgenero = "Glam Rock / Art Rock", Resena = "Un camaleón musical y cultural, Bowie constantemente reinventó su imagen y sonido, explorando géneros desde el glam hasta la electrónica.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/e/e8/David-Bowie_Chicago_2002-08-08_cropped.jpg" },
                new Artista { Id = 13, Nombre = "Bob Dylan", AlbumDestacado = "Highway 61 Revisited (1965)", CancionDestacada = "Like a Rolling Stone", Subgenero = "Folk Rock", Resena = "La voz de una generación, sus poéticas y socialmente conscientes letras transformaron la música folk y la elevaron a una forma de arte literario.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/0/02/Bob_Dylan_-_Azkena_Rock_Festival_2010_1.jpg" },
                new Artista { Id = 14, Nombre = "The Doors", AlbumDestacado = "The Doors (1967)", CancionDestacada = "Light My Fire", Subgenero = "Rock Psicodélico", Resena = "Con la poesía oscura de Jim Morrison y el sonido hipnótico de sus teclados, The Doors exploró los rincones más oscuros de la psique humana.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/7/79/The_Doors_1968.jpg" },
                new Artista { Id = 15, Nombre = "Creedence Clearwater Revival", AlbumDestacado = "Cosmo's Factory (1970)", CancionDestacada = "Fortunate Son", Subgenero = "Swamp Rock / Roots Rock", Resena = "Liderados por John Fogerty, crearon un sonido distintivo de rock sureño con éxitos concisos y potentes que se convirtieron en himnos.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/3/3e/Creedence_Clearwater_Revival_1968.jpg" },
                new Artista { Id = 16, Nombre = "Black Sabbath", AlbumDestacado = "Paranoid (1970)", CancionDestacada = "Paranoid", Subgenero = "Heavy Metal / Hard Rock", Resena = "Considerados los creadores del heavy metal, sus riffs oscuros y pesados, cortesía de Tony Iommi, sentaron las bases para todo un género.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/8/87/Black_Sabbath_1970.jpg" },
                new Artista { Id = 17, Nombre = "AC/DC", AlbumDestacado = "Back in Black (1980)", CancionDestacada = "Back in Black", Subgenero = "Hard Rock", Resena = "La personificación del rock and roll directo y sin concesiones. Su música se basa en riffs de guitarra simples, potentes y memorables.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/9/91/ACDC_in_2001.jpg" },
                new Artista { Id = 18, Nombre = "Eagles", AlbumDestacado = "Hotel California (1976)", CancionDestacada = "Hotel California", Subgenero = "Soft Rock / Country Rock", Resena = "Maestros de las armonías vocales y del sonido californiano, mezclaron el country con el soft rock para crear algunas de las canciones más vendidas de la historia.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/b/b5/Eagles_band_on_tour.jpg" },
                new Artista { Id = 19, Nombre = "Fleetwood Mac", AlbumDestacado = "Rumours (1977)", CancionDestacada = "Go Your Own Way", Subgenero = "Soft Rock / Pop Rock", Resena = "Con una mezcla única de talento británico y estadounidense, crearon pop-rock sofisticado, marcado por sus complejas relaciones internas.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/f/fe/Fleetwood_Mac_Billboard_1977.jpg" },
                new Artista { Id = 20, Nombre = "Ramones", AlbumDestacado = "Ramones (1976)", CancionDestacada = "Blitzkrieg Bop", Subgenero = "Punk Rock", Resena = "Pioneros del punk, despojaron el rock a su esencia más básica: tres acordes, velocidad y una energía cruda y contagiosa.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/6/6b/Ramones_in_Tivoli_Stockholm_1977.jpg" },
                new Artista { Id = 21, Nombre = "Sex Pistols", AlbumDestacado = "Never Mind the Bollocks...", CancionDestacada = "Anarchy in the U.K.", Subgenero = "Punk Rock", Resena = "La banda que encarnó la furia y el nihilismo del punk británico. Su breve y caótica existencia dejó una marca indeleble en la música y la cultura.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/f/ff/Sex_Pistols-publicity-shot-1977.jpg" },
                new Artista { Id = 22, Nombre = "The Clash", AlbumDestacado = "London Calling (1979)", CancionDestacada = "London Calling", Subgenero = "Punk Rock / New Wave", Resena = "Conocidos como 'la única banda que importa', fusionaron el punk con reggae, ska y rockabilly, abordando temas políticos y sociales.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/0/07/The_Clash_at_the_Lochem_Festival_1982.jpg" },
                new Artista { Id = 23, Nombre = "U2", AlbumDestacado = "The Joshua Tree (1987)", CancionDestacada = "With or Without You", Subgenero = "Alternative Rock / Post-Punk", Resena = "Desde sus raíces post-punk, se convirtieron en una de las bandas más grandes del mundo, con el sonido de guitarra de The Edge y la voz apasionada de Bono.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/b/b5/U2_in_2017.jpg" },
                new Artista { Id = 24, Nombre = "Guns N' Roses", AlbumDestacado = "Appetite for Destruction (1987)", CancionDestacada = "Sweet Child o' Mine", Subgenero = "Hard Rock", Resena = "Irrumpieron en la escena de los 80 con una peligrosa mezcla de hard rock, punk y blues, personificando el exceso del rock de estadio.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/3/3b/Guns_N%27_Roses_at_The_O2_Arena_-_2012_%282%29.jpg" },
                new Artista { Id = 25, Nombre = "Bruce Springsteen", AlbumDestacado = "Born to Run (1975)", CancionDestacada = "Born to Run", Subgenero = "Heartland Rock", Resena = "Conocido como 'The Boss', sus canciones son crónicas de la vida de la clase trabajadora estadounidense, llenas de pasión y energía rockera.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/f/f4/Bruce_Springsteen_-_Roskilde_Festival_2012.jpg" },
                new Artista { Id = 26, Nombre = "Nirvana", AlbumDestacado = "Nevermind (1991)", CancionDestacada = "Smells Like Teen Spirit", Subgenero = "Grunge / Alternative Rock", Resena = "Lideraron la revolución del grunge, cambiando el panorama musical de los 90 con su sonido que alternaba entre la apatía y la furia.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/1/19/Nirvana_around_1992.jpg" },
                new Artista { Id = 27, Nombre = "Pearl Jam", AlbumDestacado = "Ten (1991)", CancionDestacada = "Alive", Subgenero = "Grunge / Alternative Rock", Resena = "Una de las bandas más influyentes de la escena de Seattle, conocidos por la intensa voz de Eddie Vedder y su postura anti-corporativa.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/5/5e/Pearl_Jam_in_2009.jpg" },
                new Artista { Id = 28, Nombre = "R.E.M.", AlbumDestacado = "Automatic for the People (1992)", CancionDestacada = "Losing My Religion", Subgenero = "Alternative Rock", Resena = "Pioneros del rock alternativo, su sonido jangle-pop y las enigmáticas letras de Michael Stipe los llevaron del underground a la fama mundial.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/b/b0/R.E.M._Press_Conference_in_Mexico_City.jpg" },
                new Artista { Id = 29, Nombre = "Red Hot Chili Peppers", AlbumDestacado = "Californication (1999)", CancionDestacada = "Under the Bridge", Subgenero = "Funk Rock / Alternative Rock", Resena = "Fusionaron funk, punk y rock psicodélico para crear un sonido enérgico y distintivo, impulsado por la icónica línea de bajo de Flea.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/8/89/Red_Hot_Chili_Peppers_2012-08-26_Rock_en_Seine_01.jpg" },
                new Artista { Id = 30, Nombre = "Metallica", AlbumDestacado = "Master of Puppets (1986)", CancionDestacada = "Master of Puppets", Subgenero = "Thrash Metal", Resena = "Una de las bandas de heavy metal más exitosas de la historia, definieron el thrash metal con su velocidad, agresividad y complejidad musical.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/b/b7/Metallica_at_The_O2_Arena_London_2008.jpg" },
                new Artista { Id = 31, Nombre = "The Police", AlbumDestacado = "Synchronicity (1983)", CancionDestacada = "Every Breath You Take", Subgenero = "New Wave / Post-Punk", Resena = "Este trío británico mezcló rock con influencias de reggae y jazz, creando un sonido sofisticado y minimalista que dominó las radios de los 80.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/a/a4/The_Police_in_concert_in_1981_-_2.jpg" },
                new Artista { Id = 32, Nombre = "Dire Straits", AlbumDestacado = "Brothers in Arms (1985)", CancionDestacada = "Sultans of Swing", Subgenero = "Blues Rock / Roots Rock", Resena = "Liderados por la inconfundible guitarra y voz de Mark Knopfler, su sonido limpio y melódico fue un contrapunto al punk y la new wave.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/4/4b/Dire_Straits_-_Hammersmith_Odeon_1979_03.jpg" },
                new Artista { Id = 33, Nombre = "Radiohead", AlbumDestacado = "OK Computer (1997)", CancionDestacada = "Paranoid Android", Subgenero = "Alternative Rock / Art Rock", Resena = "Constantemente empujando los límites de la música rock, son conocidos por su experimentación sónica y sus temas de alienación moderna.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/2/22/Radiohead_Coachella_2017.jpg" },
                new Artista { Id = 34, Nombre = "Oasis", AlbumDestacado = "(What's the Story) Morning Glory? (1995)", CancionDestacada = "Wonderwall", Subgenero = "Britpop", Resena = "La banda insignia del movimiento Britpop de los 90, con himnos de estadio y la volátil relación entre los hermanos Gallagher en su núcleo.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/f/fb/Oasis_2008.jpg" },
                new Artista { Id = 35, Nombre = "The Smiths", AlbumDestacado = "The Queen Is Dead (1986)", CancionDestacada = "There Is a Light That Never Goes Out", Subgenero = "Jangle Pop / Indie Rock", Resena = "Definieron el sonido del rock indie británico de los 80 con las guitarras de Johnny Marr y las melancólicas letras de Morrissey.", Imagen = "https://upload.wikimedia.org/wikipedia/en/2/29/The_Smiths_promo_photo.jpg" },
                new Artista { Id = 36, Nombre = "The Cure", AlbumDestacado = "Disintegration (1989)", CancionDestacada = "Just Like Heaven", Subgenero = "Gothic Rock / New Wave", Resena = "Liderados por Robert Smith, transitaron del post-punk a un pop melancólico y atmosférico, convirtiéndose en íconos del rock gótico.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/8/87/The_Cure_in_2016.jpg" },
                new Artista { Id = 37, Nombre = "Soundgarden", AlbumDestacado = "Superunknown (1994)", CancionDestacada = "Black Hole Sun", Subgenero = "Grunge / Hard Rock", Resena = "Una de las bandas pilares del grunge, destacaron por su complejidad técnica y la increíble potencia vocal de Chris Cornell.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/e/e5/Soundgarden_Rock_am_Ring_2012.jpg" },
                new Artista { Id = 38, Nombre = "Foo Fighters", AlbumDestacado = "The Colour and the Shape (1997)", CancionDestacada = "Everlong", Subgenero = "Alternative Rock / Post-Grunge", Resena = "Nacidos de las cenizas de Nirvana, la banda de Dave Grohl se convirtió en un pilar del rock de estadio con himnos enérgicos y melódicos.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/d/d4/Foo_Fighters_at_Lollapalooza_Chile_2012.jpg" },
                new Artista { Id = 39, Nombre = "Green Day", AlbumDestacado = "Dookie (1994)", CancionDestacada = "Basket Case", Subgenero = "Pop Punk / Punk Rock", Resena = "Llevaron el pop-punk al mainstream con melodías pegadizas y una energía juvenil que revitalizó el género en los años 90.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/8/89/Green_Day_-_d.jpg" },
                new Artista { Id = 40, Nombre = "The Strokes", AlbumDestacado = "Is This It (2001)", CancionDestacada = "Last Nite", Subgenero = "Indie Rock / Garage Rock Revival", Resena = "Lideraron el resurgimiento del garage rock a principios de los 2000 con un sonido cool, minimalista y lleno de guitarras angulares.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/7/7b/The_Strokes_2006.jpg" },
                new Artista { Id = 41, Nombre = "The White Stripes", AlbumDestacado = "Elephant (2003)", CancionDestacada = "Seven Nation Army", Subgenero = "Garage Rock / Blues Rock", Resena = "Este dúo de Detroit revitalizó el blues y el garage rock con un enfoque minimalista pero potente: solo guitarra y batería.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/d/d7/The_White_Stripes_live_at_the_O2_Wireless_Festival_2007.jpg" },
                new Artista { Id = 42, Nombre = "Arctic Monkeys", AlbumDestacado = "Whatever People Say I Am...", CancionDestacada = "I Bet You Look Good on the Dancefloor", Subgenero = "Indie Rock / Post-Punk Revival", Resena = "Fueron una de las primeras bandas en saltar a la fama gracias a internet, con letras ingeniosas sobre la vida nocturna juvenil y riffs de guitarra frenéticos.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/0/08/Arctic_Monkeys_at_The_O2_Arena_%282013%29.jpg" },
                new Artista { Id = 43, Nombre = "Kings of Leon", AlbumDestacado = "Only by the Night (2008)", CancionDestacada = "Sex on Fire", Subgenero = "Alternative Rock", Resena = "Evolucionaron de un rock sureño y crudo a un sonido de rock de estadio pulido que les otorgó fama mundial a finales de los 2000.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/d/d3/Kings_of_Leon_at_the_O2_Arena%2C_2013_%283%29.jpg" },
                new Artista { Id = 44, Nombre = "Linkin Park", AlbumDestacado = "Hybrid Theory (2000)", CancionDestacada = "In the End", Subgenero = "Nu Metal / Alternative Rock", Resena = "Definieron el sonido nu-metal de los 2000 al fusionar rock, hip-hop y electrónica, con letras que conectaron con una generación de jóvenes.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/9/9f/Linkin_park_2010.jpg" },
                new Artista { Id = 45, Nombre = "Muse", AlbumDestacado = "Absolution (2003)", CancionDestacada = "Hysteria", Subgenero = "Alternative Rock / Space Rock", Resena = "Este trío británico es conocido por su sonido grandilocuente, que mezcla rock alternativo con ópera, electrónica y temas conspiranoicos.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/9/91/Muse_in_2010.jpg" },
                new Artista { Id = 46, Nombre = "Coldplay", AlbumDestacado = "A Rush of Blood to the Head (2002)", CancionDestacada = "Clocks", Subgenero = "Alternative Rock / Pop Rock", Resena = "Desde sus inicios en el rock alternativo melódico, se han convertido en una de las bandas de pop-rock más grandes del planeta.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/7/73/Coldplay_live_at_the_Rock_im_Park_2011.jpg" },
                new Artista { Id = 47, Nombre = "Tom Petty", AlbumDestacado = "Full Moon Fever (1989)", CancionDestacada = "Free Fallin'", Subgenero = "Heartland Rock", Resena = "Un maestro de la composición de canciones, Tom Petty creó un rock clásico y atemporal, con melodías que se sienten instantáneamente familiares.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/b/b5/Tom_Petty_and_the_Heartbreakers_in_2012.jpg" },
                new Artista { Id = 48, Nombre = "Janis Joplin", AlbumDestacado = "Pearl (1971)", CancionDestacada = "Me and Bobby McGee", Subgenero = "Blues Rock", Resena = "Con una voz cruda, poderosa y llena de emoción, Janis Joplin fue una de las cantantes de rock y blues más icónicas de su era.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/9/98/Janis_Joplin_in_1969_%28cropped%29.jpg" },
                new Artista { Id = 49, Nombre = "Lynyrd Skynyrd", AlbumDestacado = "(Pronounced 'Lĕh-'nérd 'Skin-'nérd')", CancionDestacada = "Sweet Home Alabama", Subgenero = "Southern Rock", Resena = "La banda por excelencia del rock sureño, conocidos por su triple ataque de guitarras y por himnos que definieron el género.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/b/b3/Lynyrd_Skynyrd_-_Cobo_Hall.jpg" },
                new Artista { Id = 50, Nombre = "Blondie", AlbumDestacado = "Parallel Lines (1978)", CancionDestacada = "Heart of Glass", Subgenero = "New Wave / Punk Rock", Resena = "Surgidos de la escena punk de Nueva York, Blondie y la icónica Debbie Harry fusionaron punk, disco y pop para dominar las listas de éxitos.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/a/a6/Blondie_-_1977.jpg" }
            );
        }
    }
}