using Microsoft.EntityFrameworkCore;
using RockProjectBackend.Models;

namespace RockProjectBackend.Data
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
        }

        public DbSet<Artista> Artistas { get; set; }

        // Dentro de tu clase AppDbContext.cs
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Artista>().HasData(
                new Artista { Id = 1, Nombre = "Elvis Presley", AlbumDestacado = "Elvis Presley (1956)", CancionDestacada = "Hound Dog", Subgenero = "Rockabilly / Rock and Roll", Resena = "Considerado el 'Rey del Rock and Roll', su carisma y su fusión de country con rhythm and blues lo convirtieron en un ícono cultural que cambió la música para siempre.", Imagen = "https://direstraitsblog.com/wp-content/uploads/2017/08/Elvis-Presley-Dancing-Photo-Share-On-Facebook.jpg" },
                new Artista { Id = 2, Nombre = "Chuck Berry", AlbumDestacado = "Chuck Berry Is on Top (1959)", CancionDestacada = "Johnny B. Goode", Subgenero = "Rock and Roll", Resena = "Uno de los padres fundadores del rock, definió su sonido con su distintiva guitarra y letras que capturaban el espíritu de la juventud estadounidense.", Imagen = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgYL3kbCF0JGUDKAK_iv1KLaojYu3v8RIq7SVnNaVJh-HewiOWhtn5qijLKSAZRVvr6VhBsXEmt7rQX80M_1AmdBFty-pSwCErjs78YrnIn_hyphenhyphen93Bl-j2zD4reZQ-GUh0lVt7EY9P8ooDg/s1600/chuck-berry-portrait.jpg" },
                new Artista { Id = 3, Nombre = "Little Richard", AlbumDestacado = "Here's Little Richard (1957)", CancionDestacada = "Tutti Frutti", Subgenero = "Rock and Roll", Resena = "Con su energía explosiva, su piano frenético y su voz inconfundible, fue una fuerza pionera que inyectó extravagancia y dinamismo al rock and roll.", Imagen = "https://images.genius.com/9075cc90590d6536cbd710a4d8d7bb2d.1000x1000x1.jpg" },
                new Artista { Id = 4, Nombre = "Buddy Holly", AlbumDestacado = "The 'Chirping' Crickets (1957)", CancionDestacada = "Peggy Sue", Subgenero = "Rockabilly", Resena = "Un innovador compositor y guitarrista cuya carrera, aunque breve, influyó profundamente en la estructura de la música pop y el formato de las bandas de rock.", Imagen = "https://wallpapers.com/images/hd/painted-portrait-of-buddy-holly-and-the-crickets-xoyaqxyy7tvwvl52.jpg" },
                new Artista { Id = 5, Nombre = "The Beatles", AlbumDestacado = "Sgt. Pepper's Lonely Hearts Club Band (1967)", CancionDestacada = "A Day in the Life", Subgenero = "Rock Psicodélico / Pop Rock", Resena = "Originarios de Liverpool, los 'Fab Four' revolucionaron la música popular con su innovadora composición, armonías vocales y experimentación en el estudio.", Imagen = "https://storage.lacapitalmdp.com/2022/10/The-Beatles.jpg" },
                new Artista { Id = 6, Nombre = "The Rolling Stones", AlbumDestacado = "Exile on Main St. (1972)", CancionDestacada = "(I Can't Get No) Satisfaction", Subgenero = "Blues Rock / Rock and Roll", Resena = "La encarnación de la rebeldía del rock, con un sonido crudo basado en el blues y una actitud que los ha mantenido como una de las bandas más grandes durante décadas.", Imagen = "https://musicscore.ms/uploads/musicscore/performer_photos/the-rolling-stones-2433.jpg" },
                new Artista { Id = 7, Nombre = "The Who", AlbumDestacado = "Who's Next (1971)", CancionDestacada = "Baba O'Riley", Subgenero = "Hard Rock / Rock", Resena = "Conocidos por sus óperas rock y sus explosivas actuaciones en vivo, The Who empujó los límites del sonido y la narrativa en la música rock.", Imagen = "https://www.thewho.com/wp-content/uploads/2017/09/1968-TheWho-Top-of-the-Pops.jpg" },
                new Artista { Id = 8, Nombre = "Led Zeppelin", AlbumDestacado = "Led Zeppelin IV (1971)", CancionDestacada = "Stairway to Heaven", Subgenero = "Hard Rock / Folk Rock", Resena = "Pioneros del hard rock y el heavy metal, esta banda británica es célebre por sus poderosos riffs de guitarra y su épica musicalidad.", Imagen = "https://i.pinimg.com/originals/36/77/8a/36778adb3057e0f53aa42b110ab2a623.jpg" },
                new Artista { Id = 9, Nombre = "Pink Floyd", AlbumDestacado = "The Dark Side of the Moon (1973)", CancionDestacada = "Money", Subgenero = "Rock Progresivo / Psicodélico", Resena = "Maestros del rock progresivo y psicodélico, son conocidos por sus álbumes conceptuales, letras filosóficas y espectáculos en vivo elaborados.", Imagen = "https://static01.nyt.com/images/2023/03/01/arts/28PINKY-FLOYD/28MOON-mediumSquareAt3X.jpg" },
                new Artista { Id = 10, Nombre = "Jimi Hendrix", AlbumDestacado = "Are You Experienced (1967)", CancionDestacada = "Purple Haze", Subgenero = "Rock Psicodélico / Hard Rock", Resena = "Considerado el guitarrista más influyente de la historia, redefinió las posibilidades del instrumento con su técnica innovadora y su uso de la distorsión y el feedback.", Imagen = "https://1.bp.blogspot.com/-k6nAovVroGw/UJdePTJDwdI/AAAAAAAAFyQ/gZS2fVR0S1E/s1600/01+jimi-hendrix.jpg" },
                new Artista { Id = 11, Nombre = "Queen", AlbumDestacado = "A Night at the Opera (1975)", CancionDestacada = "Bohemian Rhapsody", Subgenero = "Glam Rock / Hard Rock", Resena = "Liderados por el incomparable Freddie Mercury, fusionaron el glam, el hard rock y la ópera para crear un sonido grandilocuente y único.", Imagen = "https://i.pinimg.com/originals/29/02/99/290299f053e94daf1a016c3741bfff7a.jpg" },
                new Artista { Id = 12, Nombre = "David Bowie", AlbumDestacado = "The Rise and Fall of Ziggy Stardust...", CancionDestacada = "Heroes", Subgenero = "Glam Rock / Art Rock", Resena = "Un camaleón musical y cultural, Bowie constantemente reinventó su imagen y sonido, explorando géneros desde el glam hasta la electrónica.", Imagen = "https://www.rockandpop.cl/wp-content/uploads/2020/07/57e5442ffa083343d2f2b9eff320c7c9-768x791.jpg" },
                new Artista { Id = 13, Nombre = "Bob Dylan", AlbumDestacado = "Highway 61 Revisited (1965)", CancionDestacada = "Like a Rolling Stone", Subgenero = "Folk Rock", Resena = "La voz de una generación, sus poéticas y socialmente conscientes letras transformaron la música folk y la elevaron a una forma de arte literario.", Imagen = "https://a.1stdibscdn.com/lynn-goldsmith-photography-bob-dylan-straight-on-1976-for-sale/a_2432/1614719388387/dylan1_Final_master.jpg" },
                new Artista { Id = 14, Nombre = "The Doors", AlbumDestacado = "The Doors (1967)", CancionDestacada = "Light My Fire", Subgenero = "Rock Psicodélico", Resena = "Con la poesía oscura de Jim Morrison y el sonido hipnótico de sus teclados, The Doors exploró los rincones más oscuros de la psique humana.", Imagen = "https://static.stereogum.com/uploads/2015/07/the_doors.jpg" },
                new Artista { Id = 15, Nombre = "Creedence Clearwater Revival", AlbumDestacado = "Cosmo's Factory (1970)", CancionDestacada = "Fortunate Son", Subgenero = "Swamp Rock / Roots Rock", Resena = "Liderados por John Fogerty, crearon un sonido distintivo de rock sureño con éxitos concisos y potentes que se convirtieron en himnos.", Imagen = "https://www.dirtyrock.info/wp-content/uploads/2013/10/Creedence-Clearwater-Revival-reeditan-Box-set-en-noviembre.jpg" },
                new Artista { Id = 16, Nombre = "Black Sabbath", AlbumDestacado = "Paranoid (1970)", CancionDestacada = "Paranoid", Subgenero = "Heavy Metal / Hard Rock", Resena = "Considerados los creadores del heavy metal, sus riffs oscuros y pesados, cortesía de Tony Iommi, sentaron las bases para todo un género.", Imagen = "https://www.therockpit.net/wp-content/uploads/2021/08/blacksabbath-promo1-768x780.jpg" },
                new Artista { Id = 17, Nombre = "AC/DC", AlbumDestacado = "Back in Black (1980)", CancionDestacada = "Back in Black", Subgenero = "Hard Rock", Resena = "La personificación del rock and roll directo y sin concesiones. Su música se basa en riffs de guitarra simples, potentes y memorables.", Imagen = "https://images.genius.com/2c47d7d7061759b1776ba00f541392d2.1000x1000x1.jpg" },
                new Artista { Id = 18, Nombre = "Eagles", AlbumDestacado = "Hotel California (1976)", CancionDestacada = "Hotel California", Subgenero = "Soft Rock / Country Rock", Resena = "Maestros de las armonías vocales y del sonido californiano, mezclaron el country con el soft rock para crear algunas de las canciones más vendidas de la historia.", Imagen = "https://www.rollingstone.com/wp-content/uploads/2019/01/the-eagles-are-boring.jpg" },
                new Artista { Id = 19, Nombre = "Fleetwood Mac", AlbumDestacado = "Rumours (1977)", CancionDestacada = "Go Your Own Way", Subgenero = "Soft Rock / Pop Rock", Resena = "Con una mezcla única de talento británico y estadounidense, crearon pop-rock sofisticado, marcado por sus complejas relaciones internas.", Imagen = "https://cdn-images.dzcdn.net/images/artist/ef23278cf3a67a3ca8404ddaa38699d4/500x500-000000-80-0-0.jpg" },
                new Artista { Id = 20, Nombre = "Ramones", AlbumDestacado = "Ramones (1976)", CancionDestacada = "Blitzkrieg Bop", Subgenero = "Punk Rock", Resena = "Pioneros del punk, despojaron el rock a su esencia más básica: tres acordes, velocidad y una energía cruda y contagiosa.", Imagen = "https://www.rockarchive.com/media/1491/the-ramones-ra001stwa.jpg" },
                new Artista { Id = 21, Nombre = "Sex Pistols", AlbumDestacado = "Never Mind the Bollocks...", CancionDestacada = "Anarchy in the U.K.", Subgenero = "Punk Rock", Resena = "La banda que encarnó la furia y el nihilismo del punk británico. Su breve y caótica existencia dejó una marca indeleble en la música y la cultura.", Imagen = "https://www.rockarchive.com/media/1520/sex-pistols-sp001jf.jpg" },
                new Artista { Id = 22, Nombre = "The Clash", AlbumDestacado = "London Calling (1979)", CancionDestacada = "London Calling", Subgenero = "Punk Rock / New Wave", Resena = "Conocidos como 'la única banda que importa', fusionaron el punk con reggae, ska y rockabilly, abordando temas políticos y sociales.", Imagen = "https://www.rockarchive.com/media/1099/the-clash-cl001sh.jpg" },
                new Artista { Id = 23, Nombre = "U2", AlbumDestacado = "The Joshua Tree (1987)", CancionDestacada = "With or Without You", Subgenero = "Alternative Rock / Post-Punk", Resena = "Desde sus raíces post-punk, se convirtieron en una de las bandas más grandes del mundo, con el sonido de guitarra de The Edge y la voz apasionada de Bono.", Imagen = "https://www.rockarchive.com/media/1560/u2-ut007dc.jpg" },
                new Artista { Id = 24, Nombre = "Guns N' Roses", AlbumDestacado = "Appetite for Destruction (1987)", CancionDestacada = "Sweet Child o' Mine", Subgenero = "Hard Rock", Resena = "Irrumpieron en la escena de los 80 con una peligrosa mezcla de hard rock, punk y blues, personificando el exceso del rock de estadio.", Imagen = "https://ticketlive.com.co/wp-content/uploads/2025/05/1900x1900-000000-80-0-0-1024x1024.jpg" },
                new Artista { Id = 25, Nombre = "Bruce Springsteen", AlbumDestacado = "Born to Run (1975)", CancionDestacada = "Born to Run", Subgenero = "Heartland Rock", Resena = "Conocido como 'The Boss', sus canciones son crónicas de la vida de la clase trabajadora estadounidense, llenas de pasión y energía rockera.", Imagen = "https://faroutmagazine.co.uk/static/uploads/1/2024/03/Bruce-Springsteen-1980-Musician-Far-Out-Magazine-F.jpg" },
                new Artista { Id = 26, Nombre = "Nirvana", AlbumDestacado = "Nevermind (1991)", CancionDestacada = "Smells Like Teen Spirit", Subgenero = "Grunge / Alternative Rock", Resena = "Lideraron la revolución del grunge, cambiando el panorama musical de los 90 con su sonido que alternaba entre la apatía y la furia.", Imagen = "https://static.wikia.nocookie.net/the-offspring/images/6/6e/Nirvana.jpg" },
                new Artista { Id = 27, Nombre = "Pearl Jam", AlbumDestacado = "Ten (1991)", CancionDestacada = "Alive", Subgenero = "Grunge / Alternative Rock", Resena = "Una de las bandas más influyentes de la escena de Seattle, conocidos por la intensa voz de Eddie Vedder y su postura anti-corporativa.", Imagen = "https://www.cutawayguitarmagazine.com/wp-content/uploads/oldweb/art224-pearl-jam.jpg" },
                new Artista { Id = 28, Nombre = "R.E.M.", AlbumDestacado = "Automatic for the People (1992)", CancionDestacada = "Losing My Religion", Subgenero = "Alternative Rock", Resena = "Pioneros del rock alternativo, su sonido jangle-pop y las enigmáticas letras de Michael Stipe los llevaron del underground a la fama mundial.", Imagen = "https://m.media-amazon.com/images/M/MV5BYTE5ZGZjNmItNDI1Zi00OWM3LTg3NjAtOGZmOGRmOTJmMTIzXkEyXkFqcGc@._V1_.jpg" },
                new Artista { Id = 29, Nombre = "Red Hot Chili Peppers", AlbumDestacado = "Californication (1999)", CancionDestacada = "Under the Bridge", Subgenero = "Funk Rock / Alternative Rock", Resena = "Fusionaron funk, punk y rock psicodélico para crear un sonido enérgico y distintivo, impulsado por la icónica línea de bajo de Flea.", Imagen = "https://cdn.artphotolimited.com/images/63c7c308bd40b81dba379fcc/1000x1000/red-hot-chili-peppers-france-2006.jpg" },
                new Artista { Id = 30, Nombre = "Metallica", AlbumDestacado = "Master of Puppets (1986)", CancionDestacada = "Master of Puppets", Subgenero = "Thrash Metal", Resena = "Una de las bandas de heavy metal más exitosas de la historia, definieron el thrash metal con su velocidad, agresividad y complejidad musical.", Imagen = "https://images.lesindesradios.fr/fit-in/1100x2000/filters:format(webp)/radios/ouifm/importrk/2013/05/metallica-320x320.jpg" },
                new Artista { Id = 31, Nombre = "The Police", AlbumDestacado = "Synchronicity (1983)", CancionDestacada = "Every Breath You Take", Subgenero = "New Wave / Post-Punk", Resena = "Este trío británico mezcló rock con influencias de reggae y jazz, creando un sonido sofisticado y minimalista que dominó las radios de los 80.", Imagen = "https://poprockphotos.com/wp-content/uploads/2024/06/Police.-Stuart-Sting-Andy-.jpg" },
                new Artista { Id = 32, Nombre = "Dire Straits", AlbumDestacado = "Brothers in Arms (1985)", CancionDestacada = "Sultans of Swing", Subgenero = "Blues Rock / Roots Rock", Resena = "Liderados por la inconfundible guitarra y voz de Mark Knopfler, su sonido limpio y melódico fue un contrapunto al punk y la new wave.", Imagen = "https://pyxis.nymag.com/v1/imgs/828/001/1506233306eb8a79512d07edce6a528d91-dire-straits-lede-2.rhorizontal.w700.jpg" },
                new Artista { Id = 33, Nombre = "Radiohead", AlbumDestacado = "OK Computer (1997)", CancionDestacada = "Paranoid Android", Subgenero = "Alternative Rock / Art Rock", Resena = "Constantemente empujando los límites de la música rock, son conocidos por su experimentación sónica y sus temas de alienación moderna.", Imagen = "https://prensarock.com/wp-content/uploads/2016/05/radiohead_2016.jpg" },
                new Artista { Id = 34, Nombre = "Oasis", AlbumDestacado = "(What's the Story) Morning Glory? (1995)", CancionDestacada = "Wonderwall", Subgenero = "Britpop", Resena = "La banda insignia del movimiento Britpop de los 90, con himnos de estadio y la volátil relación entre los hermanos Gallagher en su núcleo.", Imagen = "https://inews.co.uk/wp-content/uploads/2024/08/SEI_218804151.jpg" },
                new Artista { Id = 35, Nombre = "The Smiths", AlbumDestacado = "The Queen Is Dead (1986)", CancionDestacada = "There Is a Light That Never Goes Out", Subgenero = "Jangle Pop / Indie Rock", Resena = "Definieron el sonido del rock indie británico de los 80 con las guitarras de Johnny Marr y las melancólicas letras de Morrissey.", Imagen = "https://standfirst-designweek-production.imgix.net/uploads/2013/07/The-Smiths.jpg" },
                new Artista { Id = 36, Nombre = "The Cure", AlbumDestacado = "Disintegration (1989)", CancionDestacada = "Just Like Heaven", Subgenero = "Gothic Rock / New Wave", Resena = "Liderados por Robert Smith, transitaron del post-punk a un pop melancólico y atmosférico, convirtiéndose en íconos del rock gótico.", Imagen = "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/3a/The_Cure.jpg" },
                new Artista { Id = 37, Nombre = "Soundgarden", AlbumDestacado = "Superunknown (1994)", CancionDestacada = "Black Hole Sun", Subgenero = "Grunge / Hard Rock", Resena = "Una de las bandas pilares del grunge, destacaron por su complejidad técnica y la increíble potencia vocal de Chris Cornell.", Imagen = "https://marvel-b1-cdn.bc0a.com/f00000000293000/rockhall.com/wp-content/uploads/2024/04/Soundgarden_Square.jpg" },
                new Artista { Id = 38, Nombre = "Foo Fighters", AlbumDestacado = "The Colour and the Shape (1997)", CancionDestacada = "Everlong", Subgenero = "Alternative Rock / Post-Grunge", Resena = "Nacidos de las cenizas de Nirvana, la banda de Dave Grohl se convirtió en un pilar del rock de estadio con himnos enérgicos y melódicos.", Imagen = "https://static01.nyt.com/images/2021/02/07/arts/07foo-fighters1/07foo-fighters1-mediumSquareAt3X-v2.jpg" },
                new Artista { Id = 39, Nombre = "Green Day", AlbumDestacado = "Dookie (1994)", CancionDestacada = "Basket Case", Subgenero = "Pop Punk / Punk Rock", Resena = "Llevaron el pop-punk al mainstream con melodías pegadizas y una energía juvenil que revitalizó el género en los años 90.", Imagen = "https://img.apmcdn.org/36722792e54dca8b68980f80b2fd3503bc3ca0d4/square/5ced62-20240129-green-day-2000.jpg" },
                new Artista { Id = 40, Nombre = "The Strokes", AlbumDestacado = "Is This It (2001)", CancionDestacada = "Last Nite", Subgenero = "Indie Rock / Garage Rock Revival", Resena = "Lideraron el resurgimiento del garage rock a principios de los 2000 con un sonido cool, minimalista y lleno de guitarras angulares.", Imagen = "https://static01.nyt.com/images/2020/04/16/arts/13strokes-review1/13strokes-review1-mediumSquareAt3X.jpg" },
                new Artista { Id = 41, Nombre = "The White Stripes", AlbumDestacado = "Elephant (2003)", CancionDestacada = "Seven Nation Army", Subgenero = "Garage Rock / Blues Rock", Resena = "Este dúo de Detroit revitalizó el blues y el garage rock con un enfoque minimalista pero potente: solo guitarra y batería.", Imagen = "https://www.rollingstone.com/wp-content/uploads/2020/06/the-white-stripes.jpg" },
                new Artista { Id = 42, Nombre = "Arctic Monkeys", AlbumDestacado = "Whatever People Say I Am...", CancionDestacada = "I Bet You Look Good on the Dancefloor", Subgenero = "Indie Rock / Post-Punk Revival", Resena = "Fueron una de las primeras bandas en saltar a la fama gracias a internet, con letras ingeniosas sobre la vida nocturna juvenil y riffs de guitarra frenéticos.", Imagen = "http://www.mxdwn.co.uk/wp-content/uploads/2013/07/2013-glastonbury-festival-guide-previews-hints-tips-and-advice_arctic-monkeys_1000PxSq72Dpi.jpeg" },
                new Artista { Id = 43, Nombre = "Kings of Leon", AlbumDestacado = "Only by the Night (2008)", CancionDestacada = "Sex on Fire", Subgenero = "Alternative Rock", Resena = "Evolucionaron de un rock sureño y crudo a un sonido de rock de estadio pulido que les otorgó fama mundial a finales de los 2000.", Imagen = "https://www.billboard.com/wp-content/uploads/media/Kings-Of-Leon-perform-Nashville-2016-billboard-1548.jpg" },
                new Artista { Id = 44, Nombre = "Linkin Park", AlbumDestacado = "Hybrid Theory (2000)", CancionDestacada = "In the End", Subgenero = "Nu Metal / Alternative Rock", Resena = "Definieron el sonido nu-metal de los 2000 al fusionar rock, hip-hop y electrónica, con letras que conectaron con una generación de jóvenes.", Imagen = "https://www.watchmojo.com/uploads/thumbs720/M-RR-Linkin-Park-480i60.jpg" },
                new Artista { Id = 45, Nombre = "Muse", AlbumDestacado = "Absolution (2003)", CancionDestacada = "Hysteria", Subgenero = "Alternative Rock / Space Rock", Resena = "Este trío británico es conocido por su sonido grandilocuente, que mezcla rock alternativo con ópera, electrónica y temas conspiranoicos.", Imagen = "https://media.npr.org/assets/img/2012/08/09/muse_custom-8180cf681271b8fd07c5fc4d6f4ed4e48a055fc6.jpg?s=1100&c=50&f=jpeg" },
                new Artista { Id = 46, Nombre = "Coldplay", AlbumDestacado = "A Rush of Blood to the Head (2002)", CancionDestacada = "Clocks", Subgenero = "Alternative Rock / Pop Rock", Resena = "Desde sus inicios en el rock alternativo melódico, se han convertido en una de las bandas de pop-rock más grandes del planeta.", Imagen = "https://tsmnoticias.com/wp-content/uploads/2015/11/Coldplay-confirma-concierto-en-Colombia.jpg" },
                new Artista { Id = 47, Nombre = "Tom Petty", AlbumDestacado = "Full Moon Fever (1989)", CancionDestacada = "Free Fallin'", Subgenero = "Heartland Rock", Resena = "Un maestro de la composición de canciones, Tom Petty creó un rock clásico y atemporal, con melodías que se sienten instantáneamente familiares.", Imagen = "https://compote.slate.com/images/0c8bffda-b045-47de-9899-df091904c5a8.jpeg" },
                new Artista { Id = 48, Nombre = "Janis Joplin", AlbumDestacado = "Pearl (1971)", CancionDestacada = "Me and Bobby McGee", Subgenero = "Blues Rock", Resena = "Con una voz cruda, poderosa y llena de emoción, Janis Joplin fue una de las cantantes de rock y blues más icónicas de su era.", Imagen = "https://cdn.prod.website-files.com/65c3e2124e0ae36491eed349/65c3e2124e0ae36491eef56a_janis-joplin-lentes.jpeg" },
                new Artista { Id = 49, Nombre = "Lynyrd Skynyrd", AlbumDestacado = "(Pronounced 'Lĕh-'nérd 'Skin-'nérd')", CancionDestacada = "Sweet Home Alabama", Subgenero = "Southern Rock", Resena = "La banda por excelencia del rock sureño, conocidos por su triple ataque de guitarras y por himnos que definieron el género.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/9/9c/Lynyrd_Skynyrd_%281977%29.jpg" },
                new Artista { Id = 50, Nombre = "Blondie", AlbumDestacado = "Parallel Lines (1978)", CancionDestacada = "Heart of Glass", Subgenero = "New Wave / Punk Rock", Resena = "Surgidos de la escena punk de Nueva York, Blondie y la icónica Debbie Harry fusionaron punk, disco y pop para dominar las listas de éxitos.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Blondie1977.jpg/1200px-Blondie1977.jpg" }
            );
        }
    }
}